spring.application.name=demo
spring.data.mongodb.uri=mongodb+srv://lounalibbrecht_db_user:e144RpTCJHJ27A9d@firstproject.hdk0szm.mongodb.net/?appName=firstProject
spring.data.mongodb.database=firstProject
server.port=8080
